apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: helseopplysninger
  name: redis
  namespace: helseopplysninger
spec:
  image: redis
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: diasight-api
