name: CI

on: push

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  NX_BASE: ""
  IMAGE_PREFIX: diasight-
  CLUSTER: labs-gcp
  SHOULD_DEPLOY: ${{ github.ref == 'refs/heads/main' || false }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      changed: ${{ steps.set-matrix.outputs.changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin main
      - run: |
          if [[ ${{ github.ref == 'refs/heads/main' }} == true ]]; then
            echo "NX_BASE=~1" >> $GITHUB_ENV
          fi
      - name: Caching Node Modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Installing Node Modules
        run: npm ci --no-audit --prefer-offline --no-optional --ignore-scripts
      - name: Caching Nx
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: cache-nx-${{ hashFiles('package.json') }}-${{ github.sha }}
          restore-keys: |
            cache-nx-${{ hashFiles('package.json') }}-
            cache-nx-
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::{\"appname\":$(npm run matrix --silent)}"
          echo "::set-output name=changed::$(npm run matrix --silent)"
      - run: npm run affected:test
      - run: npm run affected:build
      - name: Caching Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: test
    if: ${{ needs.test.outputs.changed != '[]' }}
    strategy:
      matrix: ${{fromJSON(needs.test.outputs.matrix)}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - id: tag
        run: |
          echo '::set-output name=sha::'$(git rev-parse --short HEAD)
          echo '::set-output name=base::ghcr.io/navikt/'${{ env.IMAGE_PREFIX }}${{ matrix.appname }}
      - name: Restoring Dist Folder
        uses: actions/cache@v2
        with:
          path: ./dist
          key: cache-dist-${{ github.sha }}
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: APPNAME=${{ matrix.appname }}
          push: ${{ env.SHOULD_DEPLOY }}
          tags: ${{ steps.tag.outputs.base }}:${{ steps.tag.outputs.sha }},${{ steps.tag.outputs.base }}:latest
      - name: Deploy to ${{ env.CLUSTER }}
        if: env.SHOULD_DEPLOY == 'true'
        uses: nais/deploy/actions/deploy@v1
        env:
          IMAGE: ${{ steps.tag.outputs.base }}:${{ steps.tag.outputs.sha }}
          CLUSTER: ${{ env.CLUSTER }}
          VARS: .nais/dev.json
          RESOURCE: apps/${{ matrix.appname }}/naiserator.yaml
